using Boutique.Models;
using Boutique.Utilities;
using Boutique.ViewModels;
using Xunit;

namespace Boutique.Tests;

/// <summary>
///     Tests for DistributionFileFormatter to ensure consistent file output.
/// </summary>
public class DistributionFileFormatterTests
{
    #region SPID Line Format Structure Tests

    [Fact]
    public void FormatSpidLine_ThrowsIfNoOutfit()
    {
        var entry = new DistributionEntry();
        var vm = new DistributionEntryViewModel(entry);

        Assert.Throws<ArgumentException>(() => DistributionFileFormatter.FormatSpidLine(vm));
    }

    #endregion

    #region SkyPatcher Line Format Structure Tests

    [Fact]
    public void FormatSkyPatcherLine_ThrowsIfNoOutfit()
    {
        var entry = new DistributionEntry();
        var vm = new DistributionEntryViewModel(entry);

        Assert.Throws<ArgumentException>(() => DistributionFileFormatter.FormatSkyPatcherLine(vm));
    }

    #endregion

    #region FormatTraitFilters Tests

    [Fact]
    public void FormatTraitFilters_EmptyTraits_ReturnsNull()
    {
        var traits = new SpidTraitFilters();

        var result = DistributionFileFormatter.FormatTraitFilters(traits);

        Assert.Null(result);
    }

    [Fact]
    public void FormatTraitFilters_FemaleOnly_ReturnsF()
    {
        var traits = new SpidTraitFilters { IsFemale = true };

        var result = DistributionFileFormatter.FormatTraitFilters(traits);

        Assert.Equal("F", result);
    }

    [Fact]
    public void FormatTraitFilters_MaleOnly_ReturnsM()
    {
        var traits = new SpidTraitFilters { IsFemale = false };

        var result = DistributionFileFormatter.FormatTraitFilters(traits);

        Assert.Equal("M", result);
    }

    [Fact]
    public void FormatTraitFilters_UniqueOnly_ReturnsU()
    {
        var traits = new SpidTraitFilters { IsUnique = true };

        var result = DistributionFileFormatter.FormatTraitFilters(traits);

        Assert.Equal("U", result);
    }

    [Fact]
    public void FormatTraitFilters_NonUnique_ReturnsNegativeU()
    {
        var traits = new SpidTraitFilters { IsUnique = false };

        var result = DistributionFileFormatter.FormatTraitFilters(traits);

        Assert.Equal("-U", result);
    }

    [Fact]
    public void FormatTraitFilters_ChildOnly_ReturnsC()
    {
        var traits = new SpidTraitFilters { IsChild = true };

        var result = DistributionFileFormatter.FormatTraitFilters(traits);

        Assert.Equal("C", result);
    }

    [Fact]
    public void FormatTraitFilters_NotChild_ReturnsNegativeC()
    {
        var traits = new SpidTraitFilters { IsChild = false };

        var result = DistributionFileFormatter.FormatTraitFilters(traits);

        Assert.Equal("-C", result);
    }

    [Fact]
    public void FormatTraitFilters_MultipleTraits_JoinsWithSlash()
    {
        var traits = new SpidTraitFilters { IsFemale = true, IsUnique = false, IsChild = false };

        var result = DistributionFileFormatter.FormatTraitFilters(traits);

        Assert.Equal("F/-U/-C", result);
    }

    [Fact]
    public void FormatTraitFilters_AllPositiveTraits_FormatsCorrectly()
    {
        var traits = new SpidTraitFilters
        {
            IsFemale = true,
            IsUnique = true,
            IsSummonable = true,
            IsChild = true,
            IsLeveled = true,
            IsTeammate = true,
            IsDead = true
        };

        var result = DistributionFileFormatter.FormatTraitFilters(traits);

        Assert.Equal("F/U/S/C/L/T/D", result);
    }

    [Fact]
    public void FormatTraitFilters_AllNegativeTraits_FormatsCorrectly()
    {
        var traits = new SpidTraitFilters
        {
            IsFemale = false,
            IsUnique = false,
            IsSummonable = false,
            IsChild = false,
            IsLeveled = false,
            IsTeammate = false,
            IsDead = false
        };

        var result = DistributionFileFormatter.FormatTraitFilters(traits);

        Assert.Equal("M/-U/-S/-C/-L/-T/-D", result);
    }

    #endregion

    #region GenerateFileContent Tests

    [Fact]
    public void GenerateFileContent_EmptyEntries_ReturnsHeaderOnly()
    {
        var entries = Array.Empty<DistributionEntryViewModel>();

        var result = DistributionFileFormatter.GenerateFileContent(entries, DistributionFileType.Spid);

        Assert.Contains("; Distribution File", result);
        Assert.Contains("; Generated by Boutique:", result);
        Assert.Contains("; Last Modified:", result);
    }

    [Fact]
    public void GenerateFileContent_SpidFormat_ContainsHeader()
    {
        var entries = Array.Empty<DistributionEntryViewModel>();

        var result = DistributionFileFormatter.GenerateFileContent(entries, DistributionFileType.Spid);

        var lines = result.Split(Environment.NewLine);
        Assert.Equal("; Distribution File", lines[0]);
        Assert.StartsWith("; Generated by Boutique:", lines[1]);
        Assert.StartsWith("; Last Modified:", lines[2]);
        Assert.Equal("", lines[3]);
    }

    [Fact]
    public void GenerateFileContent_SkyPatcherFormat_ContainsHeader()
    {
        var entries = Array.Empty<DistributionEntryViewModel>();

        var result = DistributionFileFormatter.GenerateFileContent(entries, DistributionFileType.SkyPatcher);

        var lines = result.Split(Environment.NewLine);
        Assert.Equal("; Distribution File", lines[0]);
        Assert.StartsWith("; Generated by Boutique:", lines[1]);
        Assert.StartsWith("; Last Modified:", lines[2]);
    }

    [Fact]
    public void GenerateFileContent_NullOutfitEntry_IsSkipped()
    {
        var entry = new DistributionEntry();
        var vm = new DistributionEntryViewModel(entry);
        // SelectedOutfit is null by default

        var result = DistributionFileFormatter.GenerateFileContent([vm], DistributionFileType.Spid);

        // Should only contain header, no outfit lines
        var lines = result.Split(Environment.NewLine).Where(l => l.StartsWith("Outfit")).ToList();
        Assert.Empty(lines);
    }

    #endregion
}
