#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Get staged .cs files (Added, Copied, Modified)
STAGED_CS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.cs$' || true)

if [ -n "$STAGED_CS_FILES" ]; then
    echo "Formatting staged C# files..."
    dotnet format style Boutique.sln --include $STAGED_CS_FILES
    
    # Re-stage the formatted files
    echo "$STAGED_CS_FILES" | xargs git add
fi
